translator:
  yandexApiUrl: https://translate.yandex.net/api/v1.5/
  requestSchema: /schema/translateRequest.json
  responseSchema: /schema/translateResponse.json

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/translator
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    hikari:
      connection-init-sql:
    initialization-mode: always
